#ifndef _MAIN_
#define _MAIN_

#define N 10

enum {
    PIPELINE_STAGE_ONE   = 0,
    PIPELINE_STAGE_TWO   = 1,
    PIPELINE_STAGE_THREE = 2,
    PIPELINE_STAGE_FOUR  = 3,
    PIPELINE_STAGE_FIVE  = 4,
    PIPELINE_STAGE_STALL = 5,
    PIPELINE_STAGE_WORK_IN_PROGRESS = 6,
    ELEMENT_STAGE_COMPLETE = 7,
    ELEMENT_STAGE_NOT_COMPLETE = 8
};

#endif /* _MAIN_ */
