all: gdf

gdf:
	mkdir -p build
	g++ -g -Wall -o build/gdf gradient-descent.cpp -std=c++17 -lm

gdf1:
	mkdir -p build
	g++ -g -Wall -o build/gdf1 gradient-descent-f1.cpp -std=c++17 -lm

gdf2:
	mkdir -p build
	g++ -g -Wall -o build/gdf2 gradient-descent-f2.cpp -std=c++17 -lm

clean:
	rm -Rf build

