all: row_row row_col col_row col_col

row_col:
	g++ -g -o row_col row_col.cpp -std=c++11

row_row:
	g++ -g -o row_row row_row.cpp -std=c++11

col_row:
	g++ -g -o col_row col_row.cpp -std=c++11

col_col:
	g++ -g -o col_col col_col.cpp -std=c++11

clean:
	rm -f row_row row_col col_row col_col