release:
	g++ -g -Wall -O3 -o main main.cpp plot.cpp point.cpp -std=c++17 -lm -lpng

debug:
	g++ -g -Wall -O3 -o main main.cpp plot.cpp point.cpp -std=c++17 -D DEBUG -lm -lpng

clean:
	rm -f main *.png
